"""Small fail-closed POSIX filesystem boundary for sealed local secrets.

The encrypted payloads stored by this package are still sensitive even when
their encryption keys are dstack-derived.  This module keeps their filesystem
handling independent of the process umask and avoids path-based check/read
races.  It intentionally rejects legacy or operator-created files that are not
owned by the current process, regular, single-link, and exactly mode ``0600``.

Every path component is inspected and opened descriptor-relatively with
``O_NOFOLLOW``.  A system alias is resolved explicitly only when it is owned by
root, the caller is not root, and its containing directory is not writable by
group or world; this accommodates immutable aliases such as macOS ``/var``
without accepting user-created intermediate symlinks.  Cooperating writers
serialize through a checked ``flock`` file.  As with every same-UID file
protocol, code that already has write authority over the private parent
directory is part of the trusted process boundary; it can otherwise replace
directory entries independently of this module.
"""

from __future__ import annotations

import fcntl
import hashlib
import os
import secrets
import stat
import threading
from contextlib import contextmanager
from pathlib import Path
from typing import Callable, Iterator


class SecureSecretFileError(OSError):
    """Raised when a sealed file cannot be accessed without weakening policy."""


_THREAD_LOCKS_GUARD = threading.Lock()
_THREAD_LOCKS: dict[str, threading.RLock] = {}


def load_or_create_secure_secret_file(
    path: str | Path,
    factory: Callable[[], bytes],
    *,
    exact_size: int,
) -> tuple[bytes, bool]:
    """Load one secure file or exclusively publish newly generated bytes.

    The second return value is true only for the process that created the
    destination.  If another process wins the creation race, its completed file
    is loaded instead of replacing its key material.
    """

    try:
        return (
            read_secure_secret_file(
                path,
                minimum=exact_size,
                maximum=exact_size,
            ),
            False,
        )
    except FileNotFoundError:
        payload = bytes(factory())
        if len(payload) != exact_size:
            raise ValueError("generated sealed secret has an invalid size")
        try:
            write_secure_secret_file(
                path,
                payload,
                minimum=exact_size,
                maximum=exact_size,
                overwrite=False,
            )
            return payload, True
        except FileExistsError:
            return (
                read_secure_secret_file(
                    path,
                    minimum=exact_size,
                    maximum=exact_size,
                ),
                False,
            )


def secure_secret_file_exists(
    path: str | Path,
    *,
    minimum: int,
    maximum: int,
) -> bool:
    """Return whether one policy-compliant file exists, rejecting unsafe files."""

    target = _target(path)
    try:
        with _opened_parent(target, create=False) as directory:
            descriptor = _open_existing(
                directory,
                target.name,
                minimum=minimum,
                maximum=maximum,
            )
    except FileNotFoundError:
        return False
    os.close(descriptor)
    return True


def read_secure_secret_file(
    path: str | Path,
    *,
    minimum: int,
    maximum: int,
) -> bytes:
    """Read through a checked no-follow descriptor and detect in-place mutation."""

    target = _target(path)
    descriptor = -1
    try:
        with _opened_parent(target, create=False) as directory:
            descriptor = _open_existing(
                directory,
                target.name,
                minimum=minimum,
                maximum=maximum,
            )
            before = os.fstat(descriptor)
            chunks: list[bytes] = []
            remaining = before.st_size
            while remaining:
                chunk = os.read(descriptor, min(remaining, 64 * 1024))
                if not chunk:
                    raise SecureSecretFileError("sealed secret file changed during read")
                chunks.append(chunk)
                remaining -= len(chunk)
            if os.read(descriptor, 1):
                raise SecureSecretFileError("sealed secret file changed during read")
            after = os.fstat(descriptor)
            _require_secret_file(after, minimum=minimum, maximum=maximum)
            if _full_identity(after) != _full_identity(before):
                raise SecureSecretFileError("sealed secret file changed during read")
            _require_matching_path(
                directory,
                target.name,
                after,
                message="sealed secret file changed during read",
            )
            return b"".join(chunks)
    except FileNotFoundError:
        raise
    except SecureSecretFileError:
        raise
    except OSError:
        raise SecureSecretFileError("sealed secret file is unavailable") from None
    finally:
        if descriptor >= 0:
            os.close(descriptor)


def write_secure_secret_file(
    path: str | Path,
    payload: bytes,
    *,
    minimum: int,
    maximum: int,
    overwrite: bool = True,
) -> None:
    """Durably publish bytes from a random owner-only temporary file.

    Normal writes use an atomic replacement after proving that the destination
    did not change since it was inspected.  ``overwrite=False`` is used for a
    locally generated wrapping key; it atomically links the completed temporary
    inode into an absent destination and never replaces an existing key.
    """

    target = _target(path)
    encoded = bytes(payload)
    if not minimum <= len(encoded) <= maximum:
        raise ValueError("sealed secret payload size is outside policy")

    descriptor = -1
    temporary = f".dnai-secret-{os.getpid()}-{secrets.token_hex(16)}.tmp"
    temporary_present = False
    with _opened_parent(target, create=True) as directory:
        with _exclusive_writer_lock(directory, target):
            initial = _existing_identity(
                directory,
                target.name,
                minimum=minimum,
                maximum=maximum,
            )
            if initial is not None and not overwrite:
                raise FileExistsError(target)
            try:
                try:
                    descriptor = os.open(
                        temporary,
                        os.O_WRONLY
                        | os.O_CREAT
                        | os.O_EXCL
                        | os.O_NOFOLLOW
                        | os.O_CLOEXEC,
                        0o600,
                        dir_fd=directory,
                    )
                except FileExistsError:
                    raise SecureSecretFileError(
                        "sealed secret temporary file already exists"
                    ) from None
                temporary_present = True
                os.fchmod(descriptor, 0o600)
                view = memoryview(encoded)
                while view:
                    written = os.write(descriptor, view)
                    if written <= 0:
                        raise OSError
                    view = view[written:]
                os.fsync(descriptor)
                temporary_details = os.fstat(descriptor)
                _require_secret_file(
                    temporary_details,
                    minimum=minimum,
                    maximum=maximum,
                )
                if temporary_details.st_size != len(encoded):
                    raise OSError
                temporary_object = _object_identity(temporary_details)
                os.close(descriptor)
                descriptor = -1

                current = _existing_identity(
                    directory,
                    target.name,
                    minimum=minimum,
                    maximum=maximum,
                )
                if current != initial:
                    raise SecureSecretFileError(
                        "sealed secret destination changed during write"
                    )

                if overwrite:
                    os.replace(
                        temporary,
                        target.name,
                        src_dir_fd=directory,
                        dst_dir_fd=directory,
                    )
                    temporary_present = False
                else:
                    try:
                        os.link(
                            temporary,
                            target.name,
                            src_dir_fd=directory,
                            dst_dir_fd=directory,
                            follow_symlinks=False,
                        )
                    except FileExistsError:
                        raise
                    except OSError:
                        raise SecureSecretFileError(
                            "sealed secret destination could not be created"
                        ) from None
                    os.unlink(temporary, dir_fd=directory)
                    temporary_present = False

                published = _existing_identity(
                    directory,
                    target.name,
                    minimum=minimum,
                    maximum=maximum,
                )
                if (
                    published is None
                    or _object_from_identity(published) != temporary_object
                ):
                    raise SecureSecretFileError(
                        "sealed secret publication is inconsistent"
                    )
                os.fsync(directory)
            except FileExistsError:
                raise
            except SecureSecretFileError:
                raise
            except OSError:
                raise SecureSecretFileError(
                    "sealed secret file could not be written"
                ) from None
            finally:
                if descriptor >= 0:
                    os.close(descriptor)
                if temporary_present:
                    try:
                        os.unlink(temporary, dir_fd=directory)
                    except FileNotFoundError:
                        pass
                    except OSError:
                        # The main operation already fails closed.  Do not replace
                        # that bounded error with cleanup-path filesystem details.
                        pass


def _target(path: str | Path) -> Path:
    target = Path(os.path.abspath(os.fspath(path)))
    if target.name in {"", ".", ".."}:
        raise SecureSecretFileError("sealed secret path is invalid")
    return target


@contextmanager
def _opened_parent(target: Path, *, create: bool) -> Iterator[int]:
    flags = (
        os.O_RDONLY
        | os.O_DIRECTORY
        | os.O_NOFOLLOW
        | os.O_CLOEXEC
    )
    descriptor = -1
    try:
        descriptor = os.open(os.path.sep, flags)
        components = list(target.parent.parts[1:])
        followed_system_aliases = 0
        while components:
            component = components.pop(0)
            try:
                component_details = os.stat(
                    component,
                    dir_fd=descriptor,
                    follow_symlinks=False,
                )
            except FileNotFoundError:
                if not create:
                    raise
                try:
                    os.mkdir(component, mode=0o700, dir_fd=descriptor)
                    os.fsync(descriptor)
                except FileExistsError:
                    # A racing creator won; inspect its object before opening.
                    pass
                component_details = os.stat(
                    component,
                    dir_fd=descriptor,
                    follow_symlinks=False,
                )
                _require_created_directory(component_details)

            if stat.S_ISLNK(component_details.st_mode):
                parent_details = os.fstat(descriptor)
                if not _trusted_system_alias(component_details, parent_details):
                    raise SecureSecretFileError(
                        "sealed secret directory contains a symlink"
                    )
                followed_system_aliases += 1
                if followed_system_aliases > 8:
                    raise SecureSecretFileError(
                        "sealed secret directory has too many system aliases"
                    )
                alias = Path(os.readlink(component, dir_fd=descriptor))
                alias_parts = list(alias.parts[1:] if alias.is_absolute() else alias.parts)
                if not alias_parts or any(part in {"", ".", ".."} for part in alias_parts):
                    raise SecureSecretFileError(
                        "sealed secret system alias is invalid"
                    )
                if alias.is_absolute():
                    os.close(descriptor)
                    descriptor = -1
                    descriptor = os.open(os.path.sep, flags)
                components = alias_parts + components
                continue

            next_descriptor = -1
            try:
                next_descriptor = os.open(component, flags, dir_fd=descriptor)
                if not stat.S_ISDIR(os.fstat(next_descriptor).st_mode):
                    raise SecureSecretFileError(
                        "sealed secret directory component is not a directory"
                    )
            except BaseException:
                if next_descriptor >= 0:
                    os.close(next_descriptor)
                raise
            os.close(descriptor)
            descriptor = next_descriptor

        details = os.fstat(descriptor)
        _require_private_parent(details)
    except FileNotFoundError:
        if descriptor >= 0:
            os.close(descriptor)
        raise
    except SecureSecretFileError:
        if descriptor >= 0:
            os.close(descriptor)
        raise
    except OSError:
        if descriptor >= 0:
            os.close(descriptor)
        raise SecureSecretFileError("sealed secret directory is unavailable") from None

    try:
        yield descriptor
    finally:
        os.close(descriptor)


@contextmanager
def _exclusive_writer_lock(directory: int, target: Path) -> Iterator[None]:
    """Serialize cooperating writers without trusting a path-opened lock."""

    lock_key = str(target)
    with _THREAD_LOCKS_GUARD:
        thread_lock = _THREAD_LOCKS.setdefault(lock_key, threading.RLock())

    digest = hashlib.sha256(target.name.encode("utf-8")).hexdigest()[:32]
    lock_name = f".dnai-secret-lock-{digest}"
    descriptor = -1
    acquired = False
    with thread_lock:
        try:
            flags = (
                os.O_RDWR
                | os.O_NONBLOCK
                | os.O_NOFOLLOW
                | os.O_CLOEXEC
            )
            try:
                descriptor = os.open(
                    lock_name,
                    flags | os.O_CREAT | os.O_EXCL,
                    0o600,
                    dir_fd=directory,
                )
                os.fchmod(descriptor, 0o600)
                os.fsync(descriptor)
                os.fsync(directory)
            except FileExistsError:
                descriptor = os.open(lock_name, flags, dir_fd=directory)

            before = os.fstat(descriptor)
            _require_lock_file(before)
            fcntl.flock(descriptor, fcntl.LOCK_EX)
            acquired = True
            after = os.fstat(descriptor)
            _require_lock_file(after)
            if _full_identity(after) != _full_identity(before):
                raise SecureSecretFileError("sealed secret writer lock changed")
            _require_matching_path(
                directory,
                lock_name,
                after,
                message="sealed secret writer lock changed",
            )
        except SecureSecretFileError:
            if descriptor >= 0:
                if acquired:
                    try:
                        fcntl.flock(descriptor, fcntl.LOCK_UN)
                    except OSError:
                        pass
                os.close(descriptor)
            raise
        except OSError:
            if descriptor >= 0:
                if acquired:
                    try:
                        fcntl.flock(descriptor, fcntl.LOCK_UN)
                    except OSError:
                        pass
                os.close(descriptor)
            raise SecureSecretFileError(
                "sealed secret writer lock is unavailable"
            ) from None

        try:
            yield
        finally:
            if descriptor >= 0:
                if acquired:
                    try:
                        fcntl.flock(descriptor, fcntl.LOCK_UN)
                    except OSError:
                        pass
                os.close(descriptor)


def _open_existing(
    directory: int,
    name: str,
    *,
    minimum: int,
    maximum: int,
) -> int:
    descriptor = -1
    try:
        descriptor = os.open(
            name,
            os.O_RDONLY
            | os.O_NONBLOCK
            | os.O_NOFOLLOW
            | os.O_CLOEXEC,
            dir_fd=directory,
        )
        details = os.fstat(descriptor)
        _require_secret_file(
            details,
            minimum=minimum,
            maximum=maximum,
        )
        _require_matching_path(
            directory,
            name,
            details,
            message="sealed secret file changed while opening",
        )
        return descriptor
    except FileNotFoundError:
        raise
    except SecureSecretFileError:
        if descriptor >= 0:
            os.close(descriptor)
        raise
    except OSError:
        if descriptor >= 0:
            os.close(descriptor)
        raise SecureSecretFileError("sealed secret file is unavailable") from None


def _existing_identity(
    directory: int,
    name: str,
    *,
    minimum: int,
    maximum: int,
) -> tuple[int, ...] | None:
    try:
        descriptor = _open_existing(
            directory,
            name,
            minimum=minimum,
            maximum=maximum,
        )
    except FileNotFoundError:
        return None
    try:
        details = os.fstat(descriptor)
        _require_secret_file(details, minimum=minimum, maximum=maximum)
        _require_matching_path(
            directory,
            name,
            details,
            message="sealed secret file changed while opening",
        )
        return _full_identity(details)
    finally:
        os.close(descriptor)


def _require_created_directory(details: os.stat_result) -> None:
    if (
        not stat.S_ISDIR(details.st_mode)
        or details.st_uid != os.geteuid()
        or stat.S_IMODE(details.st_mode) & 0o022
    ):
        raise SecureSecretFileError("created sealed secret directory is unsafe")


def _trusted_system_alias(
    alias_details: os.stat_result,
    parent_details: os.stat_result,
) -> bool:
    return (
        stat.S_ISLNK(alias_details.st_mode)
        and alias_details.st_uid == 0
        and os.geteuid() != 0
        and stat.S_ISDIR(parent_details.st_mode)
        and stat.S_IMODE(parent_details.st_mode) & 0o022 == 0
    )


def _require_private_parent(details: os.stat_result) -> None:
    if (
        not stat.S_ISDIR(details.st_mode)
        or details.st_uid != os.geteuid()
        or stat.S_IMODE(details.st_mode) & 0o022
    ):
        raise SecureSecretFileError("sealed secret directory is unsafe")


def _require_lock_file(details: os.stat_result) -> None:
    if (
        not stat.S_ISREG(details.st_mode)
        or stat.S_IMODE(details.st_mode) != 0o600
        or details.st_uid != os.geteuid()
        or details.st_nlink != 1
        or details.st_size != 0
    ):
        raise SecureSecretFileError("sealed secret writer lock is unsafe")


def _require_matching_path(
    directory: int,
    name: str,
    details: os.stat_result,
    *,
    message: str,
) -> None:
    try:
        path_details = os.stat(name, dir_fd=directory, follow_symlinks=False)
    except OSError:
        raise SecureSecretFileError(message) from None
    if _full_identity(path_details) != _full_identity(details):
        raise SecureSecretFileError(message)


def _require_secret_file(
    details: os.stat_result,
    *,
    minimum: int,
    maximum: int,
) -> None:
    if (
        not stat.S_ISREG(details.st_mode)
        or stat.S_IMODE(details.st_mode) != 0o600
        or details.st_uid != os.geteuid()
        or details.st_nlink != 1
        or not minimum <= details.st_size <= maximum
    ):
        raise SecureSecretFileError("sealed secret file is unsafe")


def _full_identity(details: os.stat_result) -> tuple[int, ...]:
    return (
        details.st_dev,
        details.st_ino,
        details.st_size,
        details.st_mtime_ns,
        details.st_ctime_ns,
        details.st_mode,
        details.st_uid,
        details.st_nlink,
    )


def _object_identity(details: os.stat_result) -> tuple[int, ...]:
    return (
        details.st_dev,
        details.st_ino,
        details.st_size,
        details.st_mode,
        details.st_uid,
        details.st_nlink,
    )


def _object_from_identity(identity: tuple[int, ...]) -> tuple[int, ...]:
    # ``_full_identity`` stores mtime/ctime between size and mode.  Rename/link
    # publication may legitimately change ctime while retaining the exact inode.
    return (
        identity[0],
        identity[1],
        identity[2],
        identity[5],
        identity[6],
        identity[7],
    )
