def require($condition; $message):
  if $condition then . else error($message) end;

def is_sha256_digest:
  type == "string"
  and test("^sha256:[0-9a-f]{64}$")
  and . != ("sha256:" + ("0" * 64));

require(($reviewEnvelopeSha256 | is_sha256_digest);
    "Tinker review-envelope hash is invalid")
| require(($finalAuthoritySha256 | is_sha256_digest);
    "Tinker final-authority hash is invalid")
| .contracts.tinkerAccountEncumbrance += {
  status: $status,
  pendingOwner: $pendingOwner,
  accountCommitment: $accountCommitment,
  maxAddBalanceWei: $maxAddBalanceWei,
  maxSpendWei: $maxSpendWei,
  perOperationCaps: true,
  custodiesFunds: false,
  approvedComposeHashes: (if $composeCount == 0 then [] else [$composeHash] end),
  approvedComposeRoot: $composeRoot,
  approvedComposeCount: $composeCount,
  managers: (if $managerCount == 0 then [] else [$manager] end),
  managerRoot: $managerRoot,
  managerCount: $managerCount,
  releasePolicyCommitment: $releaseCommitment,
  releaseMaxAddBalanceWei: $releaseMaxAddBalanceWei,
  releaseMaxSpendWei: $releaseMaxSpendWei,
  releaseComposeHashes: (if $releaseComposeCount == 0 then [] else [$composeHash] end),
  releaseComposeRoot: $releaseComposeRoot,
  releaseComposeCount: $releaseComposeCount,
  releaseManagers: (if $releaseManagerCount == 0 then [] else [$manager] end),
  releaseManagerRoot: $releaseManagerRoot,
  releaseManagerCount: $releaseManagerCount,
  pendingAccountCommitment: $pendingAccountCommitment,
  pendingMaxAddBalanceWei: $pendingMaxAddBalanceWei,
  pendingMaxSpendWei: $pendingMaxSpendWei,
  pendingComposeHashes: (if $pendingComposeCount == 0 then [] else [$composeHash] end),
  pendingComposeRoot: $pendingComposeRoot,
  pendingComposeCount: $pendingComposeCount,
  pendingManagers: (if $pendingManagerCount == 0 then [] else [$manager] end),
  pendingManagerRoot: $pendingManagerRoot,
  pendingManagerCount: $pendingManagerCount,
  releasePolicyFrozen: $releasePolicyFrozen,
  emergencyHalted: $emergencyHalted,
  pendingReleasePolicyCommitment: $pendingCommitment,
  pendingReleasePolicyActivatesAt: $pendingActivatesAt,
  policyState: $policyState,
  currentOperatorControlled: true,
  latestReleasePhase: $phase,
  latestReleaseTx: $tx,
  latestReleaseBlock: $block,
  latestReleaseRecordedAt: $recordedAt,
  latestReleaseSourceCommit: $sourceCommit,
  latestReleaseReviewEnvelopeSha256: $reviewEnvelopeSha256,
  latestReleaseFinalAuthoritySha256: $finalAuthoritySha256
}
| .tinkerReleaseHistory = ((.tinkerReleaseHistory // []) + [{
    kind: "tinker_exact_release_policy_phase",
    chainId: 84532,
    encumbranceAddress: $encumbranceAddress,
    runtimeCodeHash: $runtimeCodeHash,
    phase: $phase,
    recordedAt: $recordedAt,
    sourceCommit: $sourceCommit,
    reviewEnvelopeSha256: $reviewEnvelopeSha256,
    finalAuthoritySha256: $finalAuthoritySha256,
    transactionHash: $tx,
    blockNumber: $block,
    status: $status,
    policyState: $policyState,
    pendingOwner: $pendingOwner,
    accountCommitment: $accountCommitment,
    maxAddBalanceWei: $maxAddBalanceWei,
    maxSpendWei: $maxSpendWei,
    perOperationCaps: true,
    custodiesFunds: false,
    approvedComposeHashes: (if $composeCount == 0 then [] else [$composeHash] end),
    composeRoot: $composeRoot,
    composeCount: $composeCount,
    managers: (if $managerCount == 0 then [] else [$manager] end),
    managerRoot: $managerRoot,
    managerCount: $managerCount,
    releasePolicyCommitment: $releaseCommitment,
    releaseMaxAddBalanceWei: $releaseMaxAddBalanceWei,
    releaseMaxSpendWei: $releaseMaxSpendWei,
    releaseComposeHashes: (if $releaseComposeCount == 0 then [] else [$composeHash] end),
    releaseComposeRoot: $releaseComposeRoot,
    releaseComposeCount: $releaseComposeCount,
    releaseManagers: (if $releaseManagerCount == 0 then [] else [$manager] end),
    releaseManagerRoot: $releaseManagerRoot,
    releaseManagerCount: $releaseManagerCount,
    pendingAccountCommitment: $pendingAccountCommitment,
    pendingMaxAddBalanceWei: $pendingMaxAddBalanceWei,
    pendingMaxSpendWei: $pendingMaxSpendWei,
    pendingComposeHashes: (if $pendingComposeCount == 0 then [] else [$composeHash] end),
    pendingComposeRoot: $pendingComposeRoot,
    pendingComposeCount: $pendingComposeCount,
    pendingManagers: (if $pendingManagerCount == 0 then [] else [$manager] end),
    pendingManagerRoot: $pendingManagerRoot,
    pendingManagerCount: $pendingManagerCount,
    pendingReleasePolicyCommitment: $pendingCommitment,
    pendingReleasePolicyActivatesAt: $pendingActivatesAt,
    releasePolicyFrozen: $releasePolicyFrozen,
    emergencyHalted: $emergencyHalted
  }])
