"""Adversarial bounded-output tests: plant real-format secrets into the inputs of
every bounded response builder and assert the raw secret never appears anywhere
in the serialized output. Guards the 'only hashes/bands leave' guarantee by
construction, not by trusting the redaction regexes.
"""
from __future__ import annotations

import json
import tempfile
import unittest

from tinker_delegate.automation_receipts import AutomationOutcome, AutomationStage
from tinker_delegate.config import Settings
from tinker_delegate.tinker_keys import KeyListResult, _delete_receipt, parse_keys_table
from tinker_delegate.tinker_proxy import (
    decrypt_encrypted_proxy_token,
    generate_proxy_recipient_keypair,
    issue_encrypted_proxy_token,
)

FULL_KEY = "tml-UgYm0AVq2rgNwipFsFJrgzluHFfHtzNgyu23D9iOJBHcIyTMhTLGGcQ4onJmRdhfDAAAA"
EMAIL = "0dfbd383322230cb@cock.email"


def _serialize(obj) -> str:
    return json.dumps(obj, default=str)


def _leaks(obj, needles) -> list[str]:
    blob = _serialize(obj)
    return [n for n in needles if n in blob]


class TestKeyListBounded(unittest.TestCase):
    def test_full_key_and_email_never_egress_from_list(self):
        # Hostile row: the full tml- key value AND the account email are present
        # in the scraped text. Neither may survive into the public listing.
        rows = [[f"4666784745118498816 {FULL_KEY} Generated by Tinker Console {EMAIL} 4 days ago"]]
        out = KeyListResult(keys=parse_keys_table(rows)).to_public_dict()
        leaked = _leaks(out, [FULL_KEY, EMAIL])
        self.assertEqual(leaked, [], f"raw secret leaked into key list: {leaked}\n{out}")

    def test_delete_receipt_hashes_ref(self):
        out = _delete_receipt(FULL_KEY, AutomationOutcome.SUCCESS, AutomationStage.API_KEY_DELETED)
        self.assertEqual(_leaks(out, [FULL_KEY]), [])
        self.assertEqual(len(out["ref_hash"]), 64)


class TestProxyIssuanceBounded(unittest.TestCase):
    def test_issuance_never_egresses_raw_jwt_or_subject(self):
        tmp = tempfile.mkdtemp()
        s = Settings(
            proxy_jwt_key="11" * 32,
            proxy_approved_subjects="",
            proxy_token_store_path=tmp + "/p.enc",
            proxy_token_store_key="22" * 32,
        )
        subject = "downstream-user-SECRET-IDENTIFIER"
        priv, pub = generate_proxy_recipient_keypair()
        resp = issue_encrypted_proxy_token(
            s, subject=subject, scopes=["tinker:train"], recipient_public_key_hex=pub, ttl_seconds=900
        )
        jwt = decrypt_encrypted_proxy_token(resp, priv)  # only the recipient can get this
        # The raw JWT and raw subject must NOT be in the issuance response.
        leaked = _leaks(resp, [jwt, subject])
        self.assertEqual(leaked, [], f"issuance leaked raw material: {leaked}")
        # And the response must not contain a bare 3-segment JWT anywhere.
        blob = _serialize(resp)
        self.assertNotIn(jwt.split(".")[2], blob)  # signature segment must be absent


if __name__ == "__main__":
    unittest.main()
